GET https://elastic:H9Ek1aaA77A2SHe044q9qyI8@sbedb12f8f2bc4e74b6a87815f315654a.kb.gcp-qa-us-central1-app-1-gke.qa.cld.elstc.co:443/




POST https://elastic:H9Ek1aaA77A2SHe044q9qyI8@bedb12f8f2bc4e74b6a87815f315654a.kb.gcp-qa-us-central1-app-1-gke.qa.cld.elstc.co:9243/internal/security/users/some_testuser HTTP/1.1
kbn-xsrf: some-xsrf-token

{
  "username": "some_testuser",
  "password": "testpassword",
  "roles": []
}

