disabled:
  # Base config files, only necessary to inform config finding script

  # Serverless base config files
  - x-pack/test_serverless/api_integration/config.base.ts
  - x-pack/test_serverless/functional/config.base.ts
  - x-pack/test_serverless/shared/config.base.ts

defaultQueue: 'n2-4-spot'
enabled:
  - x-pack/test/random/path/config.ts
